### ISSUE TITLE
Installation problems on Ubuntu 12.04 Revision: 76

### ISSUE THREAD

**Issue by rami-dabain** [bullsoft/mysql-replication-listener#12]
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

```
cmake_minimum_required(VERSION 2.8)
```

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by guweigang** [comment]
@rami-dabain hi, have you used this lib in production env? recently we changed a lot, would you please have a try?
