### ISSUE TITLE
add boost dependency for asio library

### ISSUE THREAD

**Issue by guweigang** [bullsoft/mysql-replication-listener#15]
MySQL Replication Listener depend on boost:asio library, so we shall make it explicitly in CMakeLists.txt

**Comment by ideal** [comment]
但是编译的结果确实是不需要链接boost的so，有可能asio只是使用了boost的一些宏定义。

**Comment by guweigang** [comment]
@ideal 那我们应该包含这些boost文件，还是鼓励开发者安装boost？
